version: '3'
services:
  app:
    build: ./docker
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/app
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    working_dir: /var/www/app
  db:
    platform: linux/x86_64
    image: mysql:8.0
    command: mysqld --innodb_use_native_aio=0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass